server:
  port: 1000

spring:
  datasource:
    username: root
    password: root@123
    url: jdbc:mysql://123.207.210.172:3306/soa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  #给项目来个名字
  application:
    name: soa-delay-queue
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.pay.entity

#logging:
#  path: F:/logs
#  file: F:/logs/spring-boot-logging.log
#  pattern:
#    console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
#    file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n


